apiVersion: v1
kind: Pod
metadata:
  name: k8s-shared-volume
spec:

  restartPolicy: Never

  volumes:
  - name: data
    emptyDir: {}

  containers:
  - image: borosr/k8s_api
    name: api
    imagePullPolicy: Never
    ports:
      - containerPort: 3000
    volumeMounts:
      - name: data
        mountPath: /

      # - name: var-run-data
      #   mountPath: /var/run

      # - name: sys-data
      #   mountPath: /sys

      # - name: var-lib-docker-data
      #   mountPath: /var/lib/docker/

      # - name: dev-disk-data
      #   mountPath: /dev/disk/
  - image: google/cadvisor
    name: system-monitor
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: data
        mountPath: /rootfs:ro

      # - name: var-run-data
      #   mountPath: /var/run:ro

      # - name: sys-data
      #   mountPath: /sys:ro

      # - name: var-lib-docker-data
      #   mountPath: /var/lib/docker:ro
        
      # - name: dev-disk-data
      #   mountPath: /dev/disk:ro
      