apiVersion: v1
kind: Pod
metadata:
  name: k8s-shared-volume
spec:

  restartPolicy: Never

  volumes:
  - name: data
    emptyDir: {}

  containers:
  - image: borosr/k8s_api
    name: writer
    imagePullPolicy: Never
    ports:
      - containerPort: 3000
    volumeMounts:
      - name: data
        mountPath: /tmp/writer_volume

  - image: alpine
    name: reader
    command: 
      # - ls /tmp/reader_volume
      - tail
      - -f
      - /dev/null
    volumeMounts:
      - name: data
        mountPath: /tmp/reader_volume
    